### ISSUE TITLE
the rgbt-ped datasets can't be download 

### ISSUE THREAD

**Issue by weixia1** [SoonminHwang/rgbt-ped-detection#10]
hi, i want to download the rgbt datasets, but the link you provided is lost, can you give a new link,thank you.

**Comment by DefineFC** [comment]
same here

**Comment by weixia1** [comment]
@DefineFC hi，although the link from website is disappear, but luckily,  i found the _rgb-t ped_ datasets in the disk from my classmate, who has been download previous. do you want it ?

**Comment by DefineFC** [comment]
It’s really nice of you!

Shall we communicate on email? Mine is DefineFC at tju.edu.cn.
Thx in advance!

**Comment by weixia1** [comment]
the dataset is so large, _almost 38.6G_, i am failed shall it through _email_ is not enough, can you provide a better way?

**Comment by DefineFC** [comment]
Some cloud storage service would probably make it.

Maybe BaiduYun? At least we are in the same nation aren’t we😀

**Comment by weixia1** [comment]
@DefineFC  ok, after upload the _rgb-t ped_ to Baidu Yun, i notice again.

**Comment by SoonminHwang** [comment]
@weixia1 @DefineFC I'm so sorry for the inconvenience. Our dataset server is moved, so the service was not affordable during the moving. Now, the server is online. But our domain is changed from 'kaist' to 'sejong'. So you can download our dataset via following command:

        wget http://multispectral.sejong.ac.kr/pedestrian/data-kaist/videos.tar

Please consider our [README file](https://github.com/SoonminHwang/rgbt-ped-detection/tree/master/data).

I'll update all the links in a few days.

**Comment by DefineFC** [comment]
@SoonminHwang Got it! Thanks for your work.

@weixia1 Since the link is provided above, I believe it won't be necessary for us to transfer the files. But anyhow, many thanks, warm-hearted gentleman! Have a good day.
