### ISSUE TITLE
How to draw the MR curve ？

### ISSUE THREAD

**Issue by fwanglg** [SoonminHwang/rgbt-ped-detection#12]
Hi,I would like to ask how to use matlab to draw the ROC curve in your paper ?
What is the difference between the plot of the ROC curve and the dataset of Caltech?

**Comment by jzchenriver** [comment]
Hello, it seems that the download links are dead. Have you downloaded the dataset before? If yes, can you give me a copy of the dataset? Thank you very much!

**Comment by fwanglg** [comment]
Hi, do you know how to draw miss rate (ROC) curve with toolbox?

**Comment by jzchenriver** [comment]
I have't drawn a roc, but I have used python to draw a precision recall curve(PR). I think the method may be similar. 
So, can you give me a copy of the dataset? I really need it. My email is jzchenriver@gmail.com/790768042@qq.com, we can communicate with each other.

**Comment by fwanglg** [comment]
Ok, I will send you the data set after that, but it may take a while.

**Comment by jzchenriver** [comment]
Well, thank you very much!

**Comment by huaahuaa** [comment]
> Ok, I will send you the data set after that, but it may take a while.

Do you download the data at http://multispectral.kaist.ac.kr/? I can't download dataset from that link. Can you give me a copy of the dataset? I really need it. My email is h876477730@126.com. Thanks very much.

**Comment by k0942588** [comment]
> Ok, I will send you the data set after that, but it may take a while.

Can you also send me a copy of the dataset? I really need it. My email is k0942588@hotmail.com
Thank you!

**Comment by LewX** [comment]
> Hi,I would like to ask how to use matlab to draw the ROC curve in your paper ?
> What is the difference between the plot of the ROC curve and the dataset of Caltech?

Hi, How to draw ROC curve? Could you help me?

**Comment by SoonminHwang** [comment]
Sorry for the inconvenience, please see the comment in #11
You can find [a script to draw the MR curve in MLPD repo](https://github.com/sejong-rcv/MLPD-Multi-Label-Pedestrian-Detection/blob/main/evaluation_script/evaluation_script.py).
