### ISSUE TITLE
Downloadrate on the Dataset is low.

### ISSUE THREAD

**Issue by MaKaNu** [SoonminHwang/rgbt-ped-detection#15]
Your 35 GB [Data Set](http://multispectral.kaist.ac.kr/pedestrian/data-kaist/videos.tar) is still available but the Downloadrate on different system is at 200 KB/s settled. This is a pain to download. You should test your server connections. I tested your server on bitcatcha with only good results in Japan. I was sadly not able to test if your server or any other server is the issue for the slow rates. The response to europe is a hole second. Your host is slowing down. Please consider any changes.

**Comment by jveitchmichaelis** [comment]
@SoonminHwang The download link seems to be dead at the moment, is there a mirror somewhere? Thanks!

**Comment by SoonminHwang** [comment]
Sorry for the inconvenience, please see the comment in #11
