### ISSUE TITLE
Connection to the data set download address was refused.  

### ISSUE THREAD

**Issue by zhji2822** [SoonminHwang/rgbt-ped-detection#5]
I met this issue that I didn't met before, when I was trying to use the google cloud platform to download the dataset. Any help will be appreciated thank you. 

![capture](https://user-images.githubusercontent.com/28940774/49302696-0bc3a900-f485-11e8-8406-e193da550c88.PNG)

**Comment by SoonminHwang** [comment]
Sorry for the inconvenience, please see the comment in #11
