### ISSUE TITLE
download link become invalid, got 404 in 20190228

### ISSUE THREAD

**Issue by ChenMinQi** [SoonminHwang/rgbt-ped-detection#9]
download link become invalid, got 404 in 20190228

**Comment by SoonminHwang** [comment]
@ChenMinQi  I'm so sorry for the inconvenience. Our dataset server is moved, so the service was not affordable during the moving. Now, the server is online. But our domain is changed from 'kaist' to 'sejong'. So you can download our dataset via following command:

        wget http://multispectral.sejong.ac.kr/pedestrian/data-kaist/videos.tar

Please consider our [README file](https://github.com/SoonminHwang/rgbt-ped-detection/tree/master/data).

I'll update all the links in a few days.
